######################################################################
# Automatically generated by qmake (3.1) Mon Sep 1 23:35:53 2025
######################################################################

TEMPLATE = app
TARGET = progettoPao
INCLUDEPATH += .
CONFIG += c++20
QMAKE_CXXFLAGS += -std=c++20

QT += widgets
# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += JSON/JSONReader.h \
           View/mainwindow.h \
           View/ProductListWidget.h \
           View/ProductWidget.h \
           View/VideogameWidget.h \
           LogicModel/Catalog/Filter.h \
           LogicModel/Catalog/Memory.h \
           LogicModel/Products/Accessory.h \
           LogicModel/Products/Collectible.h \
           LogicModel/Products/Console.h \
           LogicModel/Products/Enums.h \
           LogicModel/Products/IncludeAllProducts.h \
           LogicModel/Products/Product.h \
           LogicModel/Products/T-shirt.h \
           LogicModel/Products/Videogame.h \
           View/Visitor/visitor.h
SOURCES += main.cpp \
           JSON/JSONReader.cpp \
           View/mainwindow.cpp \
           View/ProductListWidget.cpp \
           View/ProductWidget.cpp \
           View/VideogameWidget.cpp \
           LogicModel/Catalog/Filter.cpp \
           LogicModel/Catalog/Memory.cpp \
           LogicModel/Products/Accessory.cpp \
           LogicModel/Products/Collectible.cpp \
           LogicModel/Products/Console.cpp \
           LogicModel/Products/Enums.cpp \
           LogicModel/Products/Product.cpp \
           LogicModel/Products/T-shirt.cpp \
           LogicModel/Products/Videogame.cpp
